run:
  timeout: 5m

linters-settings:
  dupl:
    threshold: 100
  funlen:
    statements: 50
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/tlipoca9/asta)
      - blank
      - dot
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 20
  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  goimports:
    local-prefixes: github.com/tlipoca9/asta
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: snake
        toml: snake
        mapstructure: snake
  wrapcheck:
    ignoreSigRegexps:
      - errors\..*\(
      - context\..*Err\(
      - github\.com/gofiber/fiber/v2.*\(
    ignorePackageGlobs:
      - github.com/tlipoca9/asta/*

linters:
  enable:
    - asasalint
    - dupl
    - errcheck
    - funlen
    - gci
    - gocognit
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - gosec
    - govet
    - lll
    - revive
    - sloglint
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - usestdlibvars
    - unconvert
    - unused
    - wrapcheck
