// Code generated by "stringer -type=ContextKey -output=contextkey.gen.go -linecomment"; DO NOT EDIT.

package fiberx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContextKeyRequestID-1]
	_ = x[ContextKeyTraceID-2]
	_ = x[ContextKeySpanID-3]
}

const _ContextKey_name = "request_idtrace_idspan_id"

var _ContextKey_index = [...]uint8{0, 10, 18, 25}

func (i ContextKey) String() string {
	i -= 1
	if i < 0 || i >= ContextKey(len(_ContextKey_index)-1) {
		return "ContextKey(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ContextKey_name[_ContextKey_index[i]:_ContextKey_index[i+1]]
}
