[service]
name = "asta"
addr = ":8080"
shutdown_timeout = "5s"
console = true
debug = true

[database]
db_name = "asta"
username = "root"
password = "asta"
host = "localhost"
port = 3306

[cache]
address = "localhost:6379"
