version: '3.1'
services:
  db:
    restart: always
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD=asta"
      - "MYSQL_DATABASE=asta"
    ports:
      - "3306:3306"
  cache:
    restart: always
    image: redis:7.2.4-alpine
    ports:
      - '6379:6379'
